# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\POK_project\PsoC\LABs_BLE\Lab_1_1_LED.cydsn\Lab_1_1_LED.cyprj
# Date: Fri, 02 Dec 2022 11:05:32 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for D:\POK_project\PsoC\LABs_BLE\Lab_1_1_LED.cydsn\TopDesign\TopDesign.cysch
# Project: D:\POK_project\PsoC\LABs_BLE\Lab_1_1_LED.cydsn\Lab_1_1_LED.cyprj
# Date: Fri, 02 Dec 2022 11:05:29 GMT
