# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\POK_project\PsoC\LABs_BLE\Lab_3_2_UART_Led.cydsn\Lab_3_2_UART_Led.cyprj
# Date: Sun, 04 Dec 2022 00:06:09 GMT
#set_units -time ns
create_clock -name {UART_SCBCLK(FFB)} -period 6500 -waveform {0 3250} [list [get_pins {ClockBlock/ff_div_1}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {UART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 157 313} [list]
create_generated_clock -name {SPIM_IntClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 7} [list [get_pins {ClockBlock/udb_div_1}]]
create_generated_clock -name {clk} -source [get_pins {ClockBlock/hfclk}] -edges {1 60001 120001} [list [get_pins {ClockBlock/udb_div_3}]]


# Component constraints for D:\POK_project\PsoC\LABs_BLE\Lab_3_2_UART_Led.cydsn\TopDesign\TopDesign.cysch
# Project: D:\POK_project\PsoC\LABs_BLE\Lab_3_2_UART_Led.cydsn\Lab_3_2_UART_Led.cyprj
# Date: Sun, 04 Dec 2022 00:06:06 GMT
